import type { GatsbyConfig } from 'gatsby'
// remark-gfm and github-slugger are ESM-only; gatsby-config.ts is compiled to
// CommonJS, so we require pre-bundled CJS copies generated by
// `npm run build:vendor` instead of importing the packages directly.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const remarkGfm = require('./vendor/remark-gfm.cjs').default
// eslint-disable-next-line @typescript-eslint/no-var-requires
const GithubSlugger = require('./vendor/github-slugger.cjs').default

const SITE_URL = 'https://hurima90-kim.github.io'

// Uses the same github-slugger algorithm (and a fresh per-file counter, reset
// per tree) that gatsby-plugin-mdx uses internally to build `tableOfContents`
// (via mdast-util-toc), so rendered heading ids always match the TOC's #urls
// — including for Korean/emoji headings, which a naive ASCII-only slugify
// would strip or mismatch.
function rehypeSlug() {
  function getText(node: any): string {
    if (node.type === 'text') return node.value as string
    if (node.children) return (node.children as any[]).map(getText).join('')
    return ''
  }
  return function (tree: any) {
    const slugger = new GithubSlugger()
    function visit(node: any) {
      if (node.tagName && /^h[1-6]$/.test(node.tagName)) {
        if (!node.properties) node.properties = {}
        if (!node.properties.id) {
          node.properties.id = slugger.slug(getText(node))
        }
      }
      if (node.children) (node.children as any[]).forEach(visit)
    }
    visit(tree)
  }
}

const config: GatsbyConfig = {
  siteMetadata: {
    title: `주니어 개발자 킴의 테크 블로그`,
    description: `주니어 개발자 킴의 성장과정을 담아두는 기술 블로그입니다.`,
    author: `Developer Kim`,
    siteUrl: `https://hurima90-kim.github.io`,
  },
  graphqlTypegen: {
    generateOnBuild: true,
  },
  jsxRuntime: 'automatic',
  flags: {
    DEV_SSR: false,
  },
  plugins: [
    'gatsby-plugin-image',
    'gatsby-plugin-sharp',
    'gatsby-transformer-sharp',
    'gatsby-plugin-styled-components',
    'gatsby-plugin-sitemap',
    {
      resolve: 'gatsby-plugin-mdx',
      options: {
        gatsbyRemarkPlugins: [
          {
            resolve: 'gatsby-remark-images',
            options: {
              maxWidth: 800,
              quality: 80,
              linkImagesToOriginal: false,
            },
          },
        ],
        mdxOptions: {
          remarkPlugins: [remarkGfm],
          rehypePlugins: [rehypeSlug],
        },
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'posts',
        path: './content/posts/',
      },
      __key: 'posts',
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'images',
        path: './src/images/',
      },
      __key: 'images',
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'post-images',
        path: './content/images/',
      },
      __key: 'post-images',
    },
    {
      resolve: 'gatsby-plugin-canonical-urls',
      options: {
        siteUrl: SITE_URL,
        stripQueryString: true,
      },
    },
    {
      resolve: 'gatsby-plugin-robots-txt',
      options: {
        policy: [{ userAgent: '*', allow: '/' }],
      },
    },
  ],
}

export default config
